

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Lint
      run: |
        ruff check .
        black --check .

    - name: Run tests
      run: |
        pytest -q

    - name: Snapshot
      run: |
        python PROJECT_SNAPSHOT.py --no-db --show-make --max-depth 3
        cat PROJECT_SNAPSHOT.md